-- Oct 2, 2026: Media and Content services (real estate, restaurants, and hidden drone/automotive items)
-- Run once in the Supabase SQL editor (paste the contents, not the file name). Safe to run again.
-- Hidden items (drone, automotive) are saved with website_visible=false and portal_visible=false.
-- To show them later: Admin > Service Catalog > open the item > turn on Website visible and Portal visible.
insert into public.service_catalog
 (id,name,kind,category,icon,status,featured,display_order,description,pricing_model,one_time_price,recurring_price,cadence,starting_at,sales_mode,website_visible,portal_visible,promo_eligible,features,included,metadata)
values
  ('re-essentials','Listing Essentials','package','Real Estate Media','Media','Published',false,60,'The core media for a listing: photos, a floor plan and a feature walkthrough video.','One-Time',299,null,null,false,'Request First',true,true,false,'["About 25 edited photos", "Measured floor plan", "Feature highlight walkthrough video", "Delivered as one download link"]'::jsonb,'["Listing Photography", "Floor Plan", "Feature Highlight Tour"]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "package"}'::jsonb),
  ('re-agent-pro','Agent Listing Pro','package','Real Estate Media','Media','Published',false,61,'Everything in Essentials, plus an on-camera agent tour and short reels for social.','One-Time',549,null,null,false,'Request First',true,true,false,'["Everything in Listing Essentials", "Agent on-camera lifestyle tour", "2 short vertical reels", "Delivered as one download link"]'::jsonb,'["Listing Photography", "Floor Plan", "Feature Highlight Tour", "Agent On-Camera Tour", "Listing Reels"]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "package"}'::jsonb),
  ('re-agent-monthly','Agent Monthly','subscription','Real Estate Media','Media','Published',false,62,'Two listing shoots every month for busy agents.','Recurring',null,499,'Monthly',false,'Request First',true,true,false,'["2 listing shoots each month", "Photos, floor plan or walkthrough per shoot", "Priority scheduling", "Cancel any time"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "monthly"}'::jsonb),
  ('re-brokerage','Brokerage Plan','subscription','Real Estate Media','Media','Published',false,63,'A shared pool of shoots for a brokerage, used by any agent on the team.','Recurring',null,2200,'Monthly',true,'Request First',true,true,false,'["10 shoots each month, shared by your agents", "One invoice for the brokerage", "Agents book from one place", "Custom plans for larger teams"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "monthly"}'::jsonb),
  ('re-listing-photos','Listing Photography','service','Real Estate Media','Media','Published',false,64,'Edited photos of the property, ready for the MLS, Zillow and social.','One-Time',175,null,null,false,'Request First',true,true,false,'["About 25 edited photos", "Interior and exterior", "Bright, natural color editing", "Delivered as a download link"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single"}'::jsonb),
  ('re-floor-plan','Floor Plan','service','Real Estate Media','Media','Published',false,65,'A measured 2D floor plan buyers can understand at a glance.','One-Time',129,null,null,false,'Request First',true,true,false,'["Measured 2D floor plan", "Great for listings and brochures", "Add it to any photo package for $79"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single", "addOnPrice": 79}'::jsonb),
  ('re-feature-tour','Feature Highlight Tour','service','Real Estate Media','Media','Published',false,66,'A quick walkthrough-style video that moves through the home and shows off its best features.','One-Time',149,null,null,false,'Request First',true,true,false,'["Walkthrough-style video", "Smooth movement through the home", "Cut for listings and social"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single"}'::jsonb),
  ('re-agent-tour','Agent On-Camera Tour','service','Real Estate Media','Media','Published',false,67,'The agent walks through the home on camera and explains every detail.','One-Time',299,null,null,false,'Request First',true,true,false,'["Agent on camera, room by room", "Edited and ready to post", "Great for introductions and open houses"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single"}'::jsonb),
  ('re-reels','Listing Reels','service','Real Estate Media','Media','Published',false,68,'Three short vertical clips for Instagram, TikTok and Facebook.','One-Time',149,null,null,false,'Request First',true,true,false,'["3 short vertical clips", "Cut for social feeds", "Includes feature highlights"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single"}'::jsonb),
  ('re-360-tour','360 Virtual Tour','service','Real Estate Media','Media','Published',false,69,'An interactive 360 tour buyers can explore online.','One-Time',249,null,null,false,'Request First',true,true,false,'["Interactive 360 tour", "A link to share or embed", "Hosting terms confirmed when you book"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single"}'::jsonb),
  ('re-drone-photos','Drone Photos','service','Real Estate Media','Media','Published',false,70,'Aerial photos that show the property and its surroundings.','One-Time',125,null,null,false,'Request First',false,false,false,'["Aerial photos", "Edited and ready for listings"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single", "drone": true}'::jsonb),
  ('re-drone-video','Drone Video','service','Real Estate Media','Media','Published',false,71,'A short aerial video of the property and its surroundings.','One-Time',175,null,null,false,'Request First',false,false,false,'["Aerial video", "Edited and ready for listings"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single", "drone": true}'::jsonb),
  ('re-drone-bundle','Drone Bundle','service','Real Estate Media','Media','Published',false,72,'Aerial photos and video together.','One-Time',249,null,null,false,'Request First',false,false,false,'["Aerial photos", "Aerial video", "Edited and ready for listings"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "real-estate", "tier": "single", "drone": true}'::jsonb),
  ('rest-photo-refresh','Restaurant Photo Refresh','package','Restaurant Media','Media','Published',false,80,'Food, drink and interior photos for your menu, website and Google profile.','One-Time',249,null,null,false,'Request First',true,true,false,'["About 20 edited photos", "Food, drinks and interior", "Sized for web, Google and social"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "restaurant", "tier": "package"}'::jsonb),
  ('rest-social-content','Restaurant Social Content','package','Restaurant Media','Media','Published',false,81,'Photos plus short vertical clips made for social media.','One-Time',449,null,null,false,'Request First',true,true,false,'["About 20 edited photos", "4 short vertical clips", "Food, drinks and interior", "Sized for web, Google and social"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "restaurant", "tier": "package"}'::jsonb),
  ('rest-full-presence','Full Restaurant Presence','package','Restaurant Media','Media','Published',false,82,'A complete content set: photos, clips, a walkthrough and a 360 tour of the space.','One-Time',749,null,null,false,'Request First',true,true,false,'["About 30 edited photos", "6 short vertical clips", "Interior walkthrough video", "360 tour of the space"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "restaurant", "tier": "package"}'::jsonb),
  ('rest-monthly-content','Monthly Content Day','subscription','Restaurant Media','Media','Published',false,83,'One shoot each month so your content always feels fresh.','Recurring',null,399,'Monthly',false,'Request First',true,true,false,'["One shoot each month", "Photos and short clips", "Ready for social and Google", "Cancel any time"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "restaurant", "tier": "monthly"}'::jsonb),
  ('auto-inventory-day','Inventory Photo Day','service','Automotive Media','Media','Published',false,90,'A shoot day to photograph the vehicles on your lot.','One-Time',399,null,null,true,'Request First',false,false,false,'["Photos of your inventory", "Consistent angles and editing", "Ready for your listings"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "automotive", "tier": "single"}'::jsonb),
  ('auto-walkaround-reels','Walkaround Reels','service','Automotive Media','Media','Published',false,91,'Short vertical walkaround videos of featured vehicles.','One-Time',249,null,null,true,'Request First',false,false,false,'["Short vertical walkarounds", "Cut for social and listings"]'::jsonb,'[]'::jsonb,'{"family": "media", "vertical": "automotive", "tier": "single"}'::jsonb)
on conflict (id) do update set
  name=excluded.name, kind=excluded.kind, category=excluded.category, description=excluded.description,
  pricing_model=excluded.pricing_model, one_time_price=excluded.one_time_price, recurring_price=excluded.recurring_price,
  cadence=excluded.cadence, starting_at=excluded.starting_at, sales_mode=excluded.sales_mode,
  features=excluded.features, included=excluded.included, metadata=excluded.metadata, display_order=excluded.display_order, updated_at=now();
