import { read, write, type AutomationRule, type Candidate } from './automations.mts';

type Row=Record<string,any>;
export type Counts={created:number;sent:number;skipped:number;failed:number;duplicates:number};
const ADMIN='info@visionmakestudio.com';
const clients=new Map<string,Row|null>(),prefs=new Map<string,Row>();
const env=(n:string)=>Netlify.env.get(n)||'';
const clean=(v:any,n=5000)=>String(v??'').trim().slice(0,n);
const lower=(v:any)=>clean(v,240).toLowerCase();
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const defaults=()=>({email_enabled:true,in_app_enabled:true,billing:true,scheduling:true,onboarding:true,project:true,files:true,client:true});
export function resetAutomationCaches(){clients.clear();prefs.clear()}
async function getClient(id?:string|null){if(!id)return null;if(clients.has(id))return clients.get(id)||null;const r=await read(`clients?id=eq.${encodeURIComponent(id)}&select=id,business_name,contact_name,owner_email,status&limit=1`),c=r?.[0]||null;clients.set(id,c);return c}
async function getPrefs(id?:string|null){if(!id)return defaults();if(prefs.has(id))return prefs.get(id)!;const r=await read(`notification_preferences?client_id=eq.${encodeURIComponent(id)}&select=*&limit=1`).catch(()=>[]),p={...defaults(),...(r?.[0]||{})};prefs.set(id,p);return p}
async function allowed(rule:AutomationRule,c:Candidate,audience:'client'|'admin',channel:'in_app'|'email'){if(audience==='admin')return true;if(!c.clientId)return false;const p=await getPrefs(c.clientId);return p[rule.category]!==false&&(channel==='email'?p.email_enabled!==false:p.in_app_enabled!==false)}
const audiences=(r:AutomationRule)=>r.audience==='both'?['client','admin'] as const:[r.audience] as const;
const dedupe=(r:AutomationRule,c:Candidate,a:string,ch:string)=>`${r.rule_key}:${c.sourceType}:${c.sourceId}:${a}:${ch}`.slice(0,900);
async function seen(key:string,status='in.(processing,sent)'){const r=await read(`automation_deliveries?dedupe_key=eq.${encodeURIComponent(key)}&status=${status}&select=id&limit=1`);return !!r?.[0]}
async function logSkip(r:AutomationRule,c:Candidate,a:'client'|'admin',ch:'in_app'|'email',recipient:string|null,reason:string){const key=dedupe(r,c,a,ch);if(await seen(key,'eq.skipped'))return false;await write('automation_deliveries','POST',{rule_key:r.rule_key,client_id:c.clientId||null,source_type:c.sourceType,source_id:c.sourceId,audience:a,channel:ch,recipient,subject:c.subject,message:c.message,status:'skipped',dedupe_key:key,scheduled_for:c.scheduledFor||null,error:reason,metadata:{...(c.metadata||{}),preference_skip:true},updated_at:new Date().toISOString()},'return=minimal');return true}
async function claim(r:AutomationRule,c:Candidate,a:'client'|'admin',ch:'in_app'|'email',recipient:string|null){const key=dedupe(r,c,a,ch);if(await seen(key))return null;try{const rows=await write('automation_deliveries','POST',{rule_key:r.rule_key,client_id:c.clientId||null,source_type:c.sourceType,source_id:c.sourceId,audience:a,channel:ch,recipient,subject:c.subject,message:c.message,status:'processing',dedupe_key:key,scheduled_for:c.scheduledFor||null,metadata:{...(c.metadata||{}),needs_action:!!c.needsAction},attempt_count:1,last_attempt_at:new Date().toISOString(),updated_at:new Date().toISOString()});return rows?.[0]||null}catch(e:any){if(Number(e?.status)===409)return null;throw e}}
async function finish(id:string,status:'sent'|'failed',error:string|null=null){await write(`automation_deliveries?id=eq.${encodeURIComponent(id)}`,'PATCH',{status,sent_at:status==='sent'?new Date().toISOString():null,error,last_attempt_at:new Date().toISOString(),updated_at:new Date().toISOString()},'return=minimal')}
function destination(r:AutomationRule,c:Candidate,a:'client'|'admin'){const base=(env('URL')||'https://visionmakestudio.com').replace(/\/$/,'');const explicit=clean(c.metadata?.url||c.metadata?.invoice_url||c.metadata?.hosted_invoice_url,1000);if(explicit)return explicit;if(a==='admin'){if(r.category==='billing')return `${base}/admin/billing.html`;if(r.category==='scheduling'||r.category==='project')return `${base}/admin/projects.html`;if(r.category==='files')return `${base}/admin/files.html`;if(r.category==='client')return `${base}/admin/leads.html`;return `${base}/admin/activity.html`}if(r.category==='scheduling')return `${base}/portal/schedule.html`;if(r.category==='onboarding')return `${base}/portal/onboarding.html`;return `${base}/portal/`}
function html(r:AutomationRule,c:Candidate,client:Row|null,a:'client'|'admin'){const who=esc(a==='admin'?'VMS Admin':client?.business_name||client?.contact_name||'there'),link=esc(destination(r,c,a)),label=esc(c.metadata?.button_label||(a==='admin'?'Open VMS Admin':'Open VMS Portal'));return `<!doctype html><html><body style="margin:0;background:#f4f7f8;font-family:Arial,sans-serif;color:#173443"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:620px;background:#fff;border:1px solid #dfe7ea;border-radius:18px;overflow:hidden"><tr><td style="background:#003049;padding:22px 26px;color:#fff"><div style="font-size:11px;letter-spacing:.12em;color:#9fc5d5;font-weight:700">VISION MAKE STUDIO</div><div style="font-size:24px;font-weight:800;margin-top:6px">${esc(c.subject)}</div></td></tr><tr><td style="padding:26px"><p style="font-size:15px">Hi ${who},</p><div style="font-size:15px;line-height:1.65;color:#405a66">${esc(c.message).replace(/\n/g,'<br>')}</div><p style="margin:24px 0"><a href="${link}" style="display:inline-block;background:#EB5E28;color:#fff;text-decoration:none;font-size:14px;font-weight:700;padding:12px 18px;border-radius:10px">${label}</a></p><p style="font-size:12px;line-height:1.5;color:#82949d">Vision Make Studio · NJ / NYC / Tri-State<br>Questions? Reply to this email or contact info@visionmakestudio.com.</p></td></tr></table></td></tr></table></body></html>`}
async function resend(to:string,r:AutomationRule,c:Candidate,client:Row|null,a:'client'|'admin'){const key=env('RESEND_API_KEY');if(!key)throw Object.assign(new Error('RESEND_API_KEY is not configured.'),{code:'NOT_CONFIGURED'});const replyTo=clean(c.metadata?.reply_to,240)||(env('VMS_ADMIN_EMAIL')||ADMIN);const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from:env('VMS_NOTIFICATION_FROM')||'VMS Notifications <notifications@visionmakestudio.com>',to:[to],reply_to:replyTo,subject:c.subject,text:c.message,html:html(r,c,client,a)})});if(!res.ok)throw new Error(`Email provider returned ${res.status}.`)}
async function inApp(r:AutomationRule,c:Candidate,a:'client'|'admin'){if(!(await allowed(r,c,a,'in_app')))return(await logSkip(r,c,a,'in_app',null,'Client notification preference disabled this in-app alert.'))?{skipped:true}:{duplicate:true};const d=await claim(r,c,a,'in_app',null);if(!d)return{duplicate:true};try{await write('activity_events','POST',{client_id:a==='client'?c.clientId||null:null,event_type:`automation_${r.rule_key}`,title:c.subject,detail:c.message,needs_action:!!c.needsAction,resolved:false,metadata:{automation:true,rule_key:r.rule_key,delivery_id:d.id,visibility:a,target_client_id:c.clientId||null,source_type:c.sourceType,source_id:c.sourceId,...(c.metadata||{})}},'return=minimal');await finish(d.id,'sent');return{sent:true}}catch(e:any){await finish(d.id,'failed',clean(e?.message||e,1000)).catch(()=>null);return{failed:true}}}
async function email(r:AutomationRule,c:Candidate,a:'client'|'admin'){const client=await getClient(c.clientId||null),to=a==='admin'?(env('VMS_ADMIN_EMAIL')||ADMIN):lower(client?.owner_email);if(!(await allowed(r,c,a,'email')))return(await logSkip(r,c,a,'email',to||null,'Client notification preference disabled this email.'))?{skipped:true}:{duplicate:true};if(!to)return(await logSkip(r,c,a,'email',null,'No recipient email is available.'))?{skipped:true}:{duplicate:true};if(!env('RESEND_API_KEY'))return(await logSkip(r,c,a,'email',to,'RESEND_API_KEY is not configured.'))?{skipped:true}:{duplicate:true};const d=await claim(r,c,a,'email',to);if(!d)return{duplicate:true};try{await resend(to,r,c,client,a);await finish(d.id,'sent');return{sent:true}}catch(e:any){await finish(d.id,'failed',clean(e?.message||e,1000)).catch(()=>null);return{failed:true}}}
export async function deliverFinal(r:AutomationRule,c:Candidate):Promise<Counts>{const out:Counts={created:0,sent:0,skipped:0,failed:0,duplicates:0};for(const a of audiences(r)){if(a==='client'&&!c.clientId)continue;if(r.in_app_enabled){const x:any=await inApp(r,c,a);if(x.sent){out.created++;out.sent++}else if(x.skipped){out.created++;out.skipped++}else if(x.failed){out.created++;out.failed++}else out.duplicates++}if(r.email_enabled){const x:any=await email(r,c,a);if(x.sent){out.created++;out.sent++}else if(x.skipped){out.created++;out.skipped++}else if(x.failed){out.created++;out.failed++}else out.duplicates++}}return out}
export function finalCapabilities(){return{emailConfigured:!!env('RESEND_API_KEY'),emailFrom:env('VMS_NOTIFICATION_FROM')||null,adminEmail:env('VMS_ADMIN_EMAIL')||ADMIN,preferencesReady:true,eventQueue:true,eventWorkerMinutes:1,retryLimit:3}}
